---
version: '3'
services:
    dev:
        build:
            context: ./
            dockerfile: dev.Dockerfile
        volumes:
            - 'data-volume:/tmp/boxfuse/boxfuse-sample-java-war-hello/target'

    prod:
        build:
            context: ./
            dockerfile: prod.Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - dev
        volumes:
            - 'data-volume:/opt/tomcat/webapps'
volumes:
    data-volume:
...

